// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZdscspZGpMeJPvGaIbFWtlpFvTG4J3Ug',
    appId: '1:527761154655:web:ec6a7a4cd5ef7280a2f1ea',
    messagingSenderId: '527761154655',
    projectId: 'invio-ride',
    authDomain: 'invio-ride.firebaseapp.com',
    storageBucket: 'invio-ride.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjkq7nMIYLjxZ2GguD7KVbWqj27_kzMKM',
    appId: '1:527761154655:android:6d0a6f0fc75aac6fa2f1ea',
    messagingSenderId: '527761154655',
    projectId: 'invio-ride',
    storageBucket: 'invio-ride.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzNxxfZMG3rmKxvRmmhzvicAfRX8djqFE',
    appId: '1:527761154655:ios:0d085d12a2fd608fa2f1ea',
    messagingSenderId: '527761154655',
    projectId: 'invio-ride',
    storageBucket: 'invio-ride.firebasestorage.app',
    iosBundleId: 'com.example.customerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzNxxfZMG3rmKxvRmmhzvicAfRX8djqFE',
    appId: '1:527761154655:ios:0d085d12a2fd608fa2f1ea',
    messagingSenderId: '527761154655',
    projectId: 'invio-ride',
    storageBucket: 'invio-ride.firebasestorage.app',
    iosBundleId: 'com.example.customerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZdscspZGpMeJPvGaIbFWtlpFvTG4J3Ug',
    appId: '1:527761154655:web:599b868fa86b21f4a2f1ea',
    messagingSenderId: '527761154655',
    projectId: 'invio-ride',
    authDomain: 'invio-ride.firebaseapp.com',
    storageBucket: 'invio-ride.firebasestorage.app',
  );
}
